<!--
% \VignetteEngine{knitr}
% \VignetteIndexEntry{fmdatamcf7parp1: Nucleosome bound PARP1 in MCF-7 Cells Data}
% \VignetteDepends{GenomicRanges}
% \VignettePackage{fmdatamcf7parp1}
-->

# fmdatamcf7parp1: Nucleosome bound PARP1 in MCF-7 Cells Data

Authored by: **Robert M Flight** (rflight79@gmail.com) on `r Sys.Date()`

## Data Collection and Formatting

This document describes the processing to generate all the raw data used in the analysis of nucleosome bound PARP1 in MCF-7 generated by the Fondufe-Mittendorf lab at the University of Kentucky. This includes the actual unique reads of nucleosome bound PARP1, as well as expression data, methylation data, histone marks, and CTCF transcription factor binding. The processing for each one follows in the rest of this document. Although the code is not run in the generation of this vignette, all of the code was run once to process and save the data in the `RData` format.

## PARP1 Reads

The original data existed as comma delimited files (one for each chromosome)